PREFIX = '-'
HELP = 'help'
POINTS = 'points'
ADD = 'add'
REMOVE = 'remove'
SUBTRACT = 'substract'
PING = 'ping'
HOUSES = 'houses'
AVAILABLE_COMMANDS = [HELP, POINTS, ADD, REMOVE, SUBTRACT, PING, HOUSES]